In [3]:
import numpy
import pandas as pd

In [5]:
df = pd.read_csv('ice-cream.csv', sep=';')
df

         top1      t0p2      top3      top4      top5
0       арбуз  клубника   пломбир   шоколад       NaN
1       манго  клубника    яблоко  клубника    яблоко
2    клубника     арбуз  клубника       NaN       NaN
3     шоколад    яблоко  клубника   шоколад    яблоко
4    клубника   чизкейк       NaN       NaN       NaN
..        ...       ...       ...       ...       ...
135     манго    яблоко    яблоко   пломбир  клубника
136     арбуз   пломбир   шоколад    яблоко       NaN
137   чизкейк       NaN       NaN       NaN       NaN
138   чизкейк   пломбир     арбуз       NaN       NaN
139   чизкейк       NaN       NaN       NaN       NaN

[140 rows x 5 columns]

In [10]:
df.loc[1:3,['top1']]

       top1
1     манго
2  клубника
3   шоколад